name: dev_chat
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  dio: ^5.4.3+1
  internet_connection_checker: ^1.0.0+1
  device_preview: ^1.1.0
  flutter_hooks: ^0.20.5
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.4
  icons_plus: ^5.0.0
  intl: ^0.18.1
  flutter_facebook_auth: ^7.0.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.7.6
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  cloud_functions: ^4.7.6
  googleapis_auth: ^1.6.0
  flutter_launcher_icons: ^0.13.1
  encrypt: ^5.0.3
  image_gallery_saver: ^2.0.3
  # stream_video: ^0.4.2
  stream_video_flutter: ^0.4.2
  dart_jsonwebtoken: ^2.14.0
  # zego_uikit_signaling_plugin: ^2.7.10
  # zego_uikit_prebuilt_call: ^4.11.3
  # stream_video_push_notification: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter_launcher_icons:

  android: true
  ios: true
  image_path: "assets/app_logo/app_logo.png"
 

flutter:

  uses-material-design: true

  assets:
    - assets/app_logo/

