// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqqbgrSTLonhYEIRlyv5_6ttcjePk-Wuw',
    appId: '1:642694124019:web:8105d0b290cf68ec28c286',
    messagingSenderId: '642694124019',
    projectId: 'dev-chat-d75aa',
    authDomain: 'dev-chat-d75aa.firebaseapp.com',
    storageBucket: 'dev-chat-d75aa.appspot.com',
    measurementId: 'G-28CG1MS847',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirEb8_eJsHn8KtzVinldO_0oE7AbpoSQ',
    appId: '1:642694124019:android:5b327fe20269f99428c286',
    messagingSenderId: '642694124019',
    projectId: 'dev-chat-d75aa',
    storageBucket: 'dev-chat-d75aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9N7XmKHyXIICGMlvQ5g6E1oVvMnf2Dm8',
    appId: '1:642694124019:ios:aa5dfcec1107800428c286',
    messagingSenderId: '642694124019',
    projectId: 'dev-chat-d75aa',
    storageBucket: 'dev-chat-d75aa.appspot.com',
    iosBundleId: 'com.example.devChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9N7XmKHyXIICGMlvQ5g6E1oVvMnf2Dm8',
    appId: '1:642694124019:ios:aa5dfcec1107800428c286',
    messagingSenderId: '642694124019',
    projectId: 'dev-chat-d75aa',
    storageBucket: 'dev-chat-d75aa.appspot.com',
    iosBundleId: 'com.example.devChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqqbgrSTLonhYEIRlyv5_6ttcjePk-Wuw',
    appId: '1:642694124019:web:bc6b39d710be6aaf28c286',
    messagingSenderId: '642694124019',
    projectId: 'dev-chat-d75aa',
    authDomain: 'dev-chat-d75aa.firebaseapp.com',
    storageBucket: 'dev-chat-d75aa.appspot.com',
    measurementId: 'G-0B0RDTV9GD',
  );
}
