// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawU7E5y2hkdUsO-2EJBXTv_27-qcGRlA',
    appId: '1:1076843685219:web:3b4f837280d8baec825f56',
    messagingSenderId: '1076843685219',
    projectId: 'dev-chat-app-51b93',
    authDomain: 'dev-chat-app-51b93.firebaseapp.com',
    storageBucket: 'dev-chat-app-51b93.appspot.com',
    measurementId: 'G-WC66Q6DTQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcWsYC_M5pABa8CqRycc3e4R1a5-ImuoQ',
    appId: '1:1076843685219:android:a1922f8aa81bd50f825f56',
    messagingSenderId: '1076843685219',
    projectId: 'dev-chat-app-51b93',
    storageBucket: 'dev-chat-app-51b93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXnO0bF6T-fXl3DX5HvBYhbuTP7-Rydk',
    appId: '1:1076843685219:ios:792915ad1e31bac3825f56',
    messagingSenderId: '1076843685219',
    projectId: 'dev-chat-app-51b93',
    storageBucket: 'dev-chat-app-51b93.appspot.com',
    iosClientId: '1076843685219-bmu8a30d5ujv4k964c6t4agkshd3a7ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.devChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXnO0bF6T-fXl3DX5HvBYhbuTP7-Rydk',
    appId: '1:1076843685219:ios:792915ad1e31bac3825f56',
    messagingSenderId: '1076843685219',
    projectId: 'dev-chat-app-51b93',
    storageBucket: 'dev-chat-app-51b93.appspot.com',
    iosClientId: '1076843685219-bmu8a30d5ujv4k964c6t4agkshd3a7ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.devChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAawU7E5y2hkdUsO-2EJBXTv_27-qcGRlA',
    appId: '1:1076843685219:web:bbc7c556d05722be825f56',
    messagingSenderId: '1076843685219',
    projectId: 'dev-chat-app-51b93',
    authDomain: 'dev-chat-app-51b93.firebaseapp.com',
    storageBucket: 'dev-chat-app-51b93.appspot.com',
    measurementId: 'G-8ZVCVQBQ1J',
  );
}
